### ISSUE TITLE
After executing proxy-yes.bat, I am asked for my password whenever I push or pull from Visual Studio

### ISSUE THREAD

**Issue by pabrams** [esdc-devcop/ESDC-Development-Setup#14]
After executing proxy-yes.bat, I am asked for my password whenever I push or pull from Visual Studio

**Comment by s-laugh** [comment]
I haven't been using these scripts lately, its possible the ESDC image has changes that are causing this from when it was first written. Although you should be able to store the credentials in the Windows Credentials Manager.

**Comment by pabrams** [comment]
My credential manager is all screwed up now, and trying to reinstall git gives me errors.  I'll get to the bottom of it and suggest a change, or submit a PR, if appropriate.
