### ISSUE TITLE
proxy-check-hidden.vbs fails with error "Expected statement"

### ISSUE THREAD

**Issue by pabrams** [esdc-devcop/ESDC-Development-Setup#15]
I followed the directions at https://github.com/esdc-devcop/ESDC-Development-Setup/blob/master/proxy-scripts/proxy-scripts.md, but I get the following error now at startup.
(Oddly, I cannot create any "Startup" folder at Start Menu/Programs - it claims it already exists as "Start-up"?! --- I guess there is a symlink there?)

---------------------------
Windows Script Host
---------------------------
Script:	C:\Users\Paul.Abrams\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\proxy-check-hidden.vbs
Line:	6
Char:	1
Error:	Expected statement
Code:	800A0400
Source: 	Microsoft VBScript compilation error

---------------------------
OK   
---------------------------

**Comment by pabrams** [comment]
I get a similar error after removing the whitespace from the top of the downloaded file.
The file doesn't look much like vbs, to me, it looks more like html.  Did someone make a mistake when they uploaded?

**Comment by pabrams** [comment]
I also noticed there's already a startup task on my machine called ESDC_Autoproxy.  Was that added after the proxy stuff here was written?  If so, maybe it already does everything needed, because things seem to work, for me, without following the instructions at https://github.com/esdc-devcop/ESDC-Development-Setup/blob/master/proxy-scripts/proxy-scripts.md

**Comment by s-laugh** [comment]
It does seem the `Startup` folder has been changed to `Start-up`.

As for the script, I suspect that the `ESDC_Autoproxy.exe` was added to handle internet connection with and without the VPN connection back in April(ish). And this file is now conflicting with these proxy scripts in some way.

**Comment by pabrams** [comment]
I think the startup vs start-up thing is handled by symlink.

**Comment by j-paquette** [comment]
Hi,
Closing this issue because these proxy scripts are no longer recommended.
